// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

type Envelope struct {
	// ConversationID corresponds to the JSON schema field "conversation_id".
	ConversationID *string `json:"conversation_id,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// Init corresponds to the JSON schema field "init".
	Init *Init `json:"init,omitempty,omitzero"`

	// Result corresponds to the JSON schema field "result".
	Result *Result `json:"result,omitempty,omitzero"`

	// StepUpdate corresponds to the JSON schema field "step_update".
	StepUpdate *StepUpdate `json:"step_update,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type Init struct {
	// ConversationID corresponds to the JSON schema field "conversation_id".
	ConversationID *string `json:"conversation_id,omitempty,omitzero"`

	// JsonSchema corresponds to the JSON schema field "json_schema".
	JsonSchema interface{} `json:"json_schema,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type Result struct {
	// ConversationID corresponds to the JSON schema field "conversation_id".
	ConversationID *string `json:"conversation_id,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// JsonSchema corresponds to the JSON schema field "json_schema".
	JsonSchema interface{} `json:"json_schema,omitempty,omitzero"`

	// Response corresponds to the JSON schema field "response".
	Response *string `json:"response,omitempty,omitzero"`

	// Status corresponds to the JSON schema field "status".
	Status *string `json:"status,omitempty,omitzero"`

	// StructuredOutput corresponds to the JSON schema field "structured_output".
	StructuredOutput interface{} `json:"structured_output,omitempty,omitzero"`

	// Usage corresponds to the JSON schema field "usage".
	Usage interface{} `json:"usage,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type StepUpdate struct {
	// State corresponds to the JSON schema field "state".
	State *string `json:"state,omitempty,omitzero"`

	// StepIndex corresponds to the JSON schema field "step_index".
	StepIndex *int `json:"step_index,omitempty,omitzero"`

	// StepType corresponds to the JSON schema field "step_type".
	StepType *string `json:"step_type,omitempty,omitzero"`

	// TextDelta corresponds to the JSON schema field "text_delta".
	TextDelta *string `json:"text_delta,omitempty,omitzero"`

	// ToolInfo corresponds to the JSON schema field "tool_info".
	ToolInfo *ToolInfo `json:"tool_info,omitempty,omitzero"`

	// Usage corresponds to the JSON schema field "usage".
	Usage interface{} `json:"usage,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ToolInfo struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`

	// Output corresponds to the JSON schema field "output".
	Output interface{} `json:"output,omitempty,omitzero"`

	// Parameters corresponds to the JSON schema field "parameters".
	Parameters interface{} `json:"parameters,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}
