//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package graph

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __gen_jsonschema_yamlNodeToJSON(node *yaml.Node) ([]byte, error) {
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

func __gen_jsonschema_yamlToJSON(data []byte) ([]byte, error) {
	var value any
	if err := yaml.Load(data, &value, yaml.WithV4Defaults()); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Graph *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Graph
		__gen_jsonschema_compiled_Graph = compile("Graph", __zero.Schema())
	}
}

func (Graph) Schema() json.RawMessage {
	const fileName = "jsonschema/Graph.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Graph.
func (Graph) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Graph.Validate(inst)
}

// ValidateYAML validates YAML against the JSON Schema for Graph.
// YAML is interpreted using the schema's JSON property names.
func (Graph) ValidateYAML(data []byte) error {
	jsonData, err := __gen_jsonschema_yamlToJSON(data)
	if err != nil {
		return err
	}
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonData))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Graph.Validate(inst)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Graph.
func (g *Graph) UnmarshalJSON(data []byte) (err error) {
	type Alias Graph
	type Wrapper struct {
		Alias
		Nodes json.RawMessage `json:"nodes"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Graph(wrapper.Alias)

	if len(wrapper.Nodes) == 0 {
		__next.Nodes = g.Nodes
	} else {
		var __raw0 []json.RawMessage
		if err = json.Unmarshal(wrapper.Nodes, &__raw0); err != nil {
			return fmt.Errorf("field nodes: %w", err)
		}
		var __decoded0 []Node
		if __raw0 != nil {
			__decoded0 = make([]Node, len(__raw0))
		}
		for __index, __raw := range __raw0 {
			if __decoded0[__index], err = __jsonUnmarshal__graph__Node__Graph__Nodes(__raw); err != nil {
				return fmt.Errorf("field nodes[%d]: %w", __index, err)
			}
		}
		__next.Nodes = __decoded0
	}

	*g = __next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// Graph with its JSON contract.
func (g *Graph) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next Graph
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*g = next
	return nil
}
func __jsonUnmarshal__graph__Node__Graph__Nodes(data []byte) (Node, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "type")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "codergen":
		var obj CodergenNode
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	case "parallel":
		var obj ParallelNode
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	case "parallel.fan_in":
		var obj FanInNode
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	case "tool":
		var obj ToolNode
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	case "supervisor":
		var obj SupervisorNode
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
