// Code generated by polytype. DO NOT EDIT.

/**
 * Usage is cost in USD and the five token counts. It is the shape the native `session.usage.updated` event carries, and the shape the page reads. It is declared here rather than in gimble because gimble imports this package.
 */
export type Usage = {
  "cost": number;
  "tokens": Tokens;
};

/**
 * Tokens is the five token counts every adapter reports, with one meaning each. A count the provider does not report is 0: zero is a number, and nothing here says whether it was measured or absent.
 */
export type Tokens = {
  "input": number;
  "output": number;
  "reasoning": number;
  "cache": Cache;
};

/**
 * Cache is the two halves of a prompt cache: what was served from it and what was written into it.
 */
export type Cache = {
  "read": number;
  "write": number;
};
