// Code generated by skgo. DO NOT EDIT.

package skgo

import (
	"context"
	"reflect"

	"github.com/tylergannon/skgo"

	skgo0 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
	skgo2 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizltf5zhk3ttf5nxe5lojfcf2"
	skgotp0 "github.com/tylergannon/gimble/web/src"
)

// remote_guide answers src/routes/guide.remote.ts#guide, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_guide(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_guide(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// remote_scopeUsage answers src/routes/runs/[runID]/usage.remote.ts#scopeUsage, a query.live.
//
// The argument is decoded by DecodeRoot1, generated by polytype for scopeUsage's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot2, generated for its result type.
func remote_scopeUsage(ctx context.Context, call skgo.Call, yield func(any) error) error {
	if err := skgo.RequireArgument(call); err != nil {
		return err
	}
	in, err := DecodeRoot1(call.Arg)
	if err != nil {
		return skgo.BadRequest(err)
	}
	return skgo2.Skgo_scopeUsage(ctx, in, func(out skgo2.SkgoOut_scopeUsage) error {
		tree, err := EncodeRoot2(out)
		if err != nil {
			return err
		}
		return yield(tree)
	})
}

// requestedArg_scopeUsage decodes one instance's argument for skgo.Requested, with the same
// decoder remote_scopeUsage uses.
func requestedArg_scopeUsage(arg any) (any, error) {
	in, err := DecodeRoot1(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// Remotes returns every remote function declared in the app, ready to hand
// to skgo.NewRemotes.
func Remotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/guide.remote.ts",
			Name:   "guide",
			Fn:     skgo0.Skgo_guide,
			Call:   remote_guide,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindLive,
			Module:    "src/routes/runs/[runID]/usage.remote.ts",
			Name:      "scopeUsage",
			Fn:        skgo2.Skgo_scopeUsage,
			Live:      remote_scopeUsage,
			DecodeArg: requestedArg_scopeUsage,
		}),
	}
}

// load_runs_runID_page answers src/routes/runs/[runID]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_runs_runID_page(ctx context.Context) (any, error) {
	return skgo2.Skgo_load(ctx)
}

// Loads returns every server load declared in the app, ready to hand to
// skgo.NewLoads.
func Loads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/runs/[runID]/+page.server.ts", Run: load_runs_runID_page}),
	}
}

// Endpoints returns every server route declared in the app, ready to hand
// to skgo.NewEndpoints.
func Endpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}

// Transport is the app's `transport` hook: the Go half of the encode/decode
// pairs src/hooks.ts declares. Hand it to skgo.RemoteConfig.Transport and
// skgo.LoadConfig.Transport.
//
// Each key must be spelled the same here and in src/hooks.ts: it is what the
// value travels under, and a client with no decoder for it cannot read the
// response at all.
func Transport() skgo.Transport {
	return skgo.Transport{
		"RunSnapshot": {
			Type:   reflect.TypeFor[skgotp0.RunSnapshot](),
			Encode: func(v any) (any, error) { return EncodeRunSnapshot(v.(skgotp0.RunSnapshot)) },
			Decode: func(raw any) (any, error) { return DecodeRunSnapshot(raw) },
		},
	}
}
