// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

// A path that is guaranteed to be absolute and normalized (though it is not
// guaranteed to be canonicalized or exist on the filesystem).
//
// IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
// using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization
// will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf string

type AdditionalContextEntry struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind AdditionalContextKind `json:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

type AdditionalContextKind string

const AdditionalContextKindApplication AdditionalContextKind = "application"
const AdditionalContextKindUntrusted AdditionalContextKind = "untrusted"

type ApprovalsReviewer string

const ApprovalsReviewerAutoReview ApprovalsReviewer = "auto_review"
const ApprovalsReviewerGuardianSubagent ApprovalsReviewer = "guardian_subagent"
const ApprovalsReviewerUser ApprovalsReviewer = "user"

type AskForApproval interface{}

type ByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Collaboration mode for a Codex session.
type CollaborationMode struct {
	// Mode corresponds to the JSON schema field "mode".
	Mode ModeKind `json:"mode"`

	// Settings corresponds to the JSON schema field "settings".
	Settings Settings `json:"settings"`
}

type ImageDetail string

const ImageDetailAuto ImageDetail = "auto"
const ImageDetailHigh ImageDetail = "high"
const ImageDetailLow ImageDetail = "low"
const ImageDetailOriginal ImageDetail = "original"

type LegacyAppPathString string

type ModeKind string

const ModeKindDefault ModeKind = "default"
const ModeKindPlan ModeKind = "plan"

// Controls the effective multi-agent delegation instructions for a turn. `custom`
// means the configured mode hint defines the policy instead of a built-in policy.
type MultiAgentMode interface{}

type NetworkAccess string

const NetworkAccessEnabled NetworkAccess = "enabled"
const NetworkAccessRestricted NetworkAccess = "restricted"

type Personality string

const PersonalityFriendly Personality = "friendly"
const PersonalityNone Personality = "none"
const PersonalityPragmatic Personality = "pragmatic"

// A non-empty reasoning effort value advertised by the model.
type ReasoningEffort string

// A summary of the reasoning performed by the model. This can be useful for
// debugging and understanding the model's reasoning process. See
// https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
type ReasoningSummary interface{}

type SandboxPolicy interface{}

// Settings for a collaboration mode.
type Settings struct {
	// DeveloperInstructions corresponds to the JSON schema field
	// "developer_instructions".
	DeveloperInstructions SettingsDeveloperInstructions `json:"developer_instructions,omitempty,omitzero"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// ReasoningEffort corresponds to the JSON schema field "reasoning_effort".
	ReasoningEffort interface{} `json:"reasoning_effort,omitempty,omitzero"`
}

type SettingsDeveloperInstructions *string

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange TextElementByteRange `json:"byteRange"`

	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder TextElementPlaceholder `json:"placeholder,omitempty,omitzero"`
}

// Byte range in the parent `text` buffer that this element occupies.
type TextElementByteRange struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start"`
}

// Optional human-readable placeholder for the element, displayed in the UI.
type TextElementPlaceholder *string

type TurnEnvironmentParams struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd LegacyAppPathString `json:"cwd"`

	// EnvironmentID corresponds to the JSON schema field "environmentId".
	EnvironmentID string `json:"environmentId"`

	// Environment-native runtime workspace roots. Omitted defaults to `cwd`.
	RuntimeWorkspaceRoots *TurnEnvironmentParamsRuntimeWorkspaceRoots `json:"runtimeWorkspaceRoots,omitempty,omitzero"`
}

// Environment-native runtime workspace roots. Omitted defaults to `cwd`.
type TurnEnvironmentParamsRuntimeWorkspaceRoots []LegacyAppPathString

type TurnStartParams struct {
	// Override the approval policy for this turn and subsequent turns.
	ApprovalPolicy interface{} `json:"approvalPolicy,omitempty,omitzero"`

	// Override where approval requests are routed for review on this turn and
	// subsequent turns.
	ApprovalsReviewer interface{} `json:"approvalsReviewer,omitempty,omitzero"`

	// ClientUserMessageID corresponds to the JSON schema field "clientUserMessageId".
	ClientUserMessageID TurnStartParamsClientUserMessageID `json:"clientUserMessageId,omitempty,omitzero"`

	// Override the working directory for this turn and subsequent turns.
	Cwd TurnStartParamsCwd `json:"cwd,omitempty,omitzero"`

	// Override the reasoning effort for this turn and subsequent turns.
	Effort interface{} `json:"effort,omitempty,omitzero"`

	// Input corresponds to the JSON schema field "input".
	Input []UserInput `json:"input"`

	// Override the model for this turn and subsequent turns.
	Model TurnStartParamsModel `json:"model,omitempty,omitzero"`

	// Optional JSON Schema used to constrain the final assistant message for this
	// turn.
	OutputSchema interface{} `json:"outputSchema,omitempty,omitzero"`

	// Override the personality for this turn and subsequent turns.
	Personality interface{} `json:"personality,omitempty,omitzero"`

	// Override the sandbox policy for this turn and subsequent turns.
	SandboxPolicy interface{} `json:"sandboxPolicy,omitempty,omitzero"`

	// Override the service tier for this turn and subsequent turns.
	ServiceTier TurnStartParamsServiceTier `json:"serviceTier,omitempty,omitzero"`

	// Override the reasoning summary for this turn and subsequent turns.
	Summary interface{} `json:"summary,omitempty,omitzero"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`
}

type TurnStartParamsClientUserMessageID *string

type TurnStartParamsApprovalsReviewer_0 = ApprovalsReviewer

// Override the working directory for this turn and subsequent turns.
type TurnStartParamsCwd *string

type UserInput interface{}

type TurnStartParamsEffort_0 = ReasoningEffort

// Override the model for this turn and subsequent turns.
type TurnStartParamsModel *string

type TurnStartParamsPersonality_0 = Personality

// Override the service tier for this turn and subsequent turns.
type TurnStartParamsServiceTier *string

type SettingsReasoningEffort_0 = ReasoningEffort
