// Code generated by polytype. DO NOT EDIT.

/**
 * ScopeRef names one run and one scope within it. A remote function's argument is how the page says what it is watching: a query may not read the page's own URL, so the run id crosses in the argument.
 */
export type ScopeRef = {
  "runID": string;
  "scope": string;
};
